/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "railway_crossing_fsm.v:3.1-100.10" *)
module railway_crossing_fsm(clk, reset, train_sensor, train_clear, barrier_motor, red_led, green_led);
  (* src = "railway_crossing_fsm.v:60.5-98.8" *)
  wire _00_;
  (* src = "railway_crossing_fsm.v:60.5-98.8" *)
  wire _01_;
  (* src = "railway_crossing_fsm.v:60.5-98.8" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "railway_crossing_fsm.v:8.16-8.29" *)
  output barrier_motor;
  wire barrier_motor;
  (* src = "railway_crossing_fsm.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "railway_crossing_fsm.v:10.16-10.25" *)
  output green_led;
  wire green_led;
  (* src = "railway_crossing_fsm.v:20.22-20.32" *)
  wire [2:0] next_state;
  (* src = "railway_crossing_fsm.v:9.16-9.23" *)
  output red_led;
  wire red_led;
  (* src = "railway_crossing_fsm.v:5.11-5.16" *)
  input reset;
  wire reset;
  (* src = "railway_crossing_fsm.v:20.15-20.20" *)
  wire [2:0] state;
  (* src = "railway_crossing_fsm.v:7.11-7.22" *)
  input train_clear;
  wire train_clear;
  (* src = "railway_crossing_fsm.v:6.11-6.23" *)
  input train_sensor;
  wire train_sensor;
  INVX1 _18_ (
    .A(state[2]),
    .Y(_09_)
  );
  INVX1 _19_ (
    .A(state[0]),
    .Y(_10_)
  );
  INVX1 _20_ (
    .A(train_clear),
    .Y(_11_)
  );
  INVX1 _21_ (
    .A(reset),
    .Y(_03_)
  );
  NOR2X1 _22_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_12_)
  );
  NAND2X1 _23_ (
    .A(state[2]),
    .B(_12_),
    .Y(_13_)
  );
  NAND2X1 _24_ (
    .A(_09_),
    .B(state[1]),
    .Y(_01_)
  );
  INVX1 _25_ (
    .A(_01_),
    .Y(_02_)
  );
  OAI21X1 _26_ (
    .A(state[0]),
    .B(_01_),
    .C(_13_),
    .Y(_00_)
  );
  OAI21X1 _27_ (
    .A(_10_),
    .B(_11_),
    .C(_02_),
    .Y(_14_)
  );
  NAND3X1 _28_ (
    .A(_09_),
    .B(train_sensor),
    .C(_12_),
    .Y(_15_)
  );
  NAND2X1 _29_ (
    .A(_14_),
    .B(_15_),
    .Y(next_state[0])
  );
  NAND2X1 _30_ (
    .A(_09_),
    .B(state[0]),
    .Y(_16_)
  );
  OAI21X1 _31_ (
    .A(state[1]),
    .B(_16_),
    .C(_14_),
    .Y(next_state[1])
  );
  NAND3X1 _32_ (
    .A(state[0]),
    .B(train_clear),
    .C(_02_),
    .Y(_17_)
  );
  INVX1 _33_ (
    .A(_17_),
    .Y(next_state[2])
  );
  INVX1 _34_ (
    .A(reset),
    .Y(_04_)
  );
  INVX1 _35_ (
    .A(reset),
    .Y(_05_)
  );
  INVX1 _36_ (
    .A(reset),
    .Y(_06_)
  );
  INVX1 _37_ (
    .A(reset),
    .Y(_07_)
  );
  INVX1 _38_ (
    .A(reset),
    .Y(_08_)
  );
  (* src = "railway_crossing_fsm.v:60.5-98.8" *)
  DFFSR _39_ (
    .CLK(clk),
    .D(_00_),
    .Q(barrier_motor),
    .R(_03_),
    .S(1'h1)
  );
  (* src = "railway_crossing_fsm.v:60.5-98.8" *)
  DFFSR _40_ (
    .CLK(clk),
    .D(_02_),
    .Q(red_led),
    .R(_04_),
    .S(1'h1)
  );
  (* src = "railway_crossing_fsm.v:60.5-98.8" *)
  DFFSR _41_ (
    .CLK(clk),
    .D(_01_),
    .Q(green_led),
    .R(1'h1),
    .S(_05_)
  );
  (* src = "railway_crossing_fsm.v:23.5-28.8" *)
  DFFSR _42_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(state[0]),
    .R(_06_),
    .S(1'h1)
  );
  (* src = "railway_crossing_fsm.v:23.5-28.8" *)
  DFFSR _43_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(state[1]),
    .R(_07_),
    .S(1'h1)
  );
  (* src = "railway_crossing_fsm.v:23.5-28.8" *)
  DFFSR _44_ (
    .CLK(clk),
    .D(next_state[2]),
    .Q(state[2]),
    .R(_08_),
    .S(1'h1)
  );
endmodule
